export const DEFAULT_CATEGORY_ICON = "other" as const;

export const ALL_CATEGORY_ICONS = [
  "shopping_bag",
  "groceries",
  "serving_dish",
  "coffee",
  "bubble_tea",
  "cutlery",
  "pizza",
  "burger",
  "milk_fruit",
  "bread",
  "birthday_cake",
  "donut",
  "household_goods",
  "clothing",
  "shoes",
  "shopping_cart",
  "home",
  "electricity",
  "water",
  "gas",
  "internet",
  "phone",
  "entertainment",
  "insurance",
  "car",
  "motorcycle",
  "fuel",
  "train",
  "bus",
  "flight",
  "parking",
  "taxi",
  "health",
  "medicine",
  "doctor",
  "fitness",
  "education",
  "graduation",
  "work",
  "laptop",
  "wallet",
  "savings",
  "piggy_bank",
  "income",
  "investment",
  "gift",
  "travel_ticket",
  "vacation",
  "mosque",
  "charity",
  "cash_wallet",
  "bank",
  "family",
  "pet",
  "plant",
  "other",
] as const;

export type CategoryIconName = (typeof ALL_CATEGORY_ICONS)[number];

export const CATEGORY_ICON_MAP: Record<CategoryIconName, number> = {
  shopping_bag: require("@/assets/icons/shopping_bag.png"),
  groceries: require("@/assets/icons/groceries.png"),
  serving_dish: require("@/assets/icons/serving_dish.png"),
  coffee: require("@/assets/icons/coffee.png"),
  bubble_tea: require("@/assets/icons/bubble_tea.png"),
  cutlery: require("@/assets/icons/cutlery.png"),
  pizza: require("@/assets/icons/pizza.png"),
  burger: require("@/assets/icons/burger.png"),
  milk_fruit: require("@/assets/icons/milk_fruit.png"),
  bread: require("@/assets/icons/bread.png"),
  birthday_cake: require("@/assets/icons/birthday_cake.png"),
  donut: require("@/assets/icons/donut.png"),
  household_goods: require("@/assets/icons/household_goods.png"),
  clothing: require("@/assets/icons/clothing.png"),
  shoes: require("@/assets/icons/shoes.png"),
  shopping_cart: require("@/assets/icons/shopping_cart.png"),
  home: require("@/assets/icons/home.png"),
  electricity: require("@/assets/icons/electricity.png"),
  water: require("@/assets/icons/water.png"),
  gas: require("@/assets/icons/gas.png"),
  internet: require("@/assets/icons/internet.png"),
  phone: require("@/assets/icons/phone.png"),
  entertainment: require("@/assets/icons/entertainment.png"),
  insurance: require("@/assets/icons/insurance.png"),
  car: require("@/assets/icons/car.png"),
  motorcycle: require("@/assets/icons/motorcycle.png"),
  fuel: require("@/assets/icons/fuel.png"),
  train: require("@/assets/icons/train.png"),
  bus: require("@/assets/icons/bus.png"),
  flight: require("@/assets/icons/flight.png"),
  parking: require("@/assets/icons/parking.png"),
  taxi: require("@/assets/icons/taxi.png"),
  health: require("@/assets/icons/health.png"),
  medicine: require("@/assets/icons/medicine.png"),
  doctor: require("@/assets/icons/doctor.png"),
  fitness: require("@/assets/icons/fitness.png"),
  education: require("@/assets/icons/education.png"),
  graduation: require("@/assets/icons/graduation.png"),
  work: require("@/assets/icons/work.png"),
  laptop: require("@/assets/icons/laptop.png"),
  wallet: require("@/assets/icons/wallet.png"),
  savings: require("@/assets/icons/savings.png"),
  piggy_bank: require("@/assets/icons/piggy_bank.png"),
  income: require("@/assets/icons/income.png"),
  investment: require("@/assets/icons/investment.png"),
  gift: require("@/assets/icons/gift.png"),
  travel_ticket: require("@/assets/icons/travel_ticket.png"),
  vacation: require("@/assets/icons/vacation.png"),
  mosque: require("@/assets/icons/mosque.png"),
  charity: require("@/assets/icons/charity.png"),
  cash_wallet: require("@/assets/icons/cash_wallet.png"),
  bank: require("@/assets/icons/bank.png"),
  family: require("@/assets/icons/family.png"),
  pet: require("@/assets/icons/pet.png"),
  plant: require("@/assets/icons/plant.png"),
  other: require("@/assets/icons/other.png"),
};

export function isValidCategoryIcon(name: string): name is CategoryIconName {
  return (ALL_CATEGORY_ICONS as readonly string[]).includes(name);
}

export function getCategoryIconSource(name?: string): number {
  if (name && isValidCategoryIcon(name)) return CATEGORY_ICON_MAP[name];
  return CATEGORY_ICON_MAP[DEFAULT_CATEGORY_ICON];
}
