export const DEFAULT_CATEGORY_ICON = "other" as const;

export const ALL_CATEGORY_ICONS = [
  "shopping_bag",
  "groceries",
  "serving_dish",
  "coffee",
  "bubble_tea",
  "cutlery",
  "pizza",
  "burger",
  "milk_fruit",
  "bread",
  "birthday_cake",
  "donut",
  "household_goods",
  "clothing",
  "shoes",
  "shopping_cart",
  "home",
  "electricity",
  "water",
  "gas",
  "internet",
  "phone",
  "entertainment",
  "insurance",
  "car",
  "motorcycle",
  "fuel",
  "train",
  "bus",
  "flight",
  "parking",
  "taxi",
  "health",
  "medicine",
  "doctor",
  "fitness",
  "education",
  "graduation",
  "work",
  "laptop",
  "wallet",
  "savings",
  "piggy_bank",
  "income",
  "investment",
  "gift",
  "travel_ticket",
  "vacation",
  "mosque",
  "charity",
  "cash_wallet",
  "bank",
  "family",
  "pet",
  "plant",
  "other",
] as const;

export type CategoryIconName = (typeof ALL_CATEGORY_ICONS)[number];

export function isValidCategoryIcon(name: string): name is CategoryIconName {
  return (ALL_CATEGORY_ICONS as readonly string[]).includes(name);
}
