/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      fontSize: {
        display: ["28px", { lineHeight: "1.0", letterSpacing: "-0.02em", fontWeight: "700" }],
        heading: ["18px", { lineHeight: "1.33", letterSpacing: "-0.02em", fontWeight: "700" }],
        subheading: ["15px", { lineHeight: "1.33", letterSpacing: "-0.01em", fontWeight: "500" }],
        body: ["16px", { lineHeight: "1.25", letterSpacing: "-0.01em", fontWeight: "500" }],
        label: ["14px", { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "600" }],
        detail: ["13px", { lineHeight: "1.33", letterSpacing: "0.04em", fontWeight: "400" }],
        caption: ["12px", { lineHeight: "1.33", letterSpacing: "0.02em", fontWeight: "400" }],
        micro: ["11px", { lineHeight: "1.0", letterSpacing: "0.08em", fontWeight: "600" }],
        nav: ["11px", { lineHeight: "1.0", letterSpacing: "0.02em", fontWeight: "600" }],
      },
      colors: {
        primary: "#92400E",
        "primary-light": "#FDE68A",
        background: "#FFFBF5",
        surface: "#FEF3C7",
        "text-primary": "#1C1917",
        "text-secondary": "#6E675F",
        success: "#065F46",
        error: "#991B1B",
        border: "#E7E5E4",
        "primary-dark": "#F59E0B",
        "primary-light-dark": "#78350F",
        "background-dark": "#1C1917",
        "surface-dark": "#292524",
        "text-primary-dark": "#FAF9F7",
        "text-secondary-dark": "#A8A29E",
        "success-dark": "#34D399",
        "error-dark": "#F87171",
        "border-dark": "#44403C",
      },
    },
  },
  plugins: [],
};
